server:
  port: 5000

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/}solyankabot
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345678}
  application:
    name: solyanka-bot
  data:
    hibernate:
      ddl-auto: none
#    redis:
#      database: ${REDIS_DB:0}
#      host: ${DB_HOST:localhost}
#      port: ${DB_PORT:6379}
#      password: ${DB_PASS:12345678}

telegram:
  api-url: https://api.telegram.org/
  webhook-path: null
  bot-name: quiz_solyanka_bot
  bot-token: "${BOT_TOKEN:}"